//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioProduccion {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Procedimientos : global::System.Configuration.ApplicationSettingsBase {
        
        private static Procedimientos defaultInstance = ((Procedimientos)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Procedimientos())));
        
        public static Procedimientos Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SP_T250CREARTOKEN")]
        public string SP_T250CREARTOKEN {
            get {
                return ((string)(this["SP_T250CREARTOKEN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SP_T250CONSULTARTOKEN")]
        public string SP_T250CONSULTARTOKEN {
            get {
                return ((string)(this["SP_T250CONSULTARTOKEN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SP_T250ELIMINARTOKEN")]
        public string SP_T250ELIMINARTOKEN {
            get {
                return ((string)(this["SP_T250ELIMINARTOKEN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SP_LOGIN")]
        public string SP_LOGIN {
            get {
                return ((string)(this["SP_LOGIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SP_T013LEEATRIBUTOSUSUARIO")]
        public string SP_T013LEEATRIBUTOSUSUARIO {
            get {
                return ((string)(this["SP_T013LEEATRIBUTOSUSUARIO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SP_T008TIPOBUS")]
        public string SP_T008TIPOBUS {
            get {
                return ((string)(this["SP_T008TIPOBUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SP_T005OFICINAS_VENTAS")]
        public string SP_T005OFICINAS_VENTAS {
            get {
                return ((string)(this["SP_T005OFICINAS_VENTAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SP_T026VALORRUTATIPOBUSRUTA_Venta")]
        public string SP_T026VALORRUTATIPOBUSRUTA_Venta {
            get {
                return ((string)(this["SP_T026VALORRUTATIPOBUSRUTA_Venta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SP_T011RUTASPPAL_NOMBRE_ORI")]
        public string SP_T011RUTASPPAL_NOMBRE_ORI {
            get {
                return ((string)(this["SP_T011RUTASPPAL_NOMBRE_ORI"]));
            }
        }
    }
}
