//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioProduccion {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Procedimientos : global::System.Configuration.ApplicationSettingsBase {
        
        private static Procedimientos defaultInstance = ((Procedimientos)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Procedimientos())));
        
        public static Procedimientos Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_CrearToken")]
        public string sp_CrearToken {
            get {
                return ((string)(this["sp_CrearToken"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_ObtenerTokenPorUsuario")]
        public string sp_ObtenerTokenPorUsuario {
            get {
                return ((string)(this["sp_ObtenerTokenPorUsuario"]));
            }
            set {
                this["sp_ObtenerTokenPorUsuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_ObtenerTokenPorToken")]
        public string sp_ObtenerTokenPorToken {
            get {
                return ((string)(this["sp_ObtenerTokenPorToken"]));
            }
            set {
                this["sp_ObtenerTokenPorToken"] = value;
            }
        }
    }
}
