//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorConfiguracion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSettings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorConfiguracion.AppSettings", typeof(AppSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a codigoAplicacion.
        /// </summary>
        internal static string codigoAplicacion {
            get {
                return ResourceManager.GetString("codigoAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a comentarioAplicacion.
        /// </summary>
        internal static string comentarioAplicacion {
            get {
                return ResourceManager.GetString("comentarioAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a conexion.
        /// </summary>
        internal static string conexion {
            get {
                return ResourceManager.GetString("conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a diasVencimiento.
        /// </summary>
        internal static string diasVencimiento {
            get {
                return ResourceManager.GetString("diasVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a repositorio.
        /// </summary>
        internal static string repositorio {
            get {
                return ResourceManager.GetString("repositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rutaArchivoResumenZPL.
        /// </summary>
        internal static string rutaArchivoResumenZPL {
            get {
                return ResourceManager.GetString("rutaArchivoResumenZPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rutaArchivoTiqueteZPL.
        /// </summary>
        internal static string rutaArchivoTiqueteZPL {
            get {
                return ResourceManager.GetString("rutaArchivoTiqueteZPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sistemaFactura.
        /// </summary>
        internal static string sistemaFactura {
            get {
                return ResourceManager.GetString("sistemaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sistemaSeguridad.
        /// </summary>
        internal static string sistemaSeguridad {
            get {
                return ResourceManager.GetString("sistemaSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tokenPruebas.
        /// </summary>
        internal static string tokenPruebas {
            get {
                return ResourceManager.GetString("tokenPruebas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a valorToken.
        /// </summary>
        internal static string valorToken {
            get {
                return ResourceManager.GetString("valorToken", resourceCulture);
            }
        }
    }
}
